---
title: "Modèles linéaires"
author: "Florent Chuffart & Magali Richard"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
urlcolor: blue
---


```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
# README RStudio config, uncheck: # preferences > R Markdown > show output inline for... 
```

# Avant Propos


## Organisation prévisionnelle

  - Séance 1 : Rappels info/algo 
  - Séance 2 : Régression linéaire simple 
  - Séance 3 : Régression linéaire multiple 
  - Séance 5 : TP ([Compte-rendu de TP pré-rempli](https://github.com/fchuffar/starting_kit_expred3.0))
  - Séance 4 : ANOVA 


```{r child = "0Intro_cours_modlin.Rmd", eval=TRUE}
```


```{r child = "00_cours_modlin.Rmd", eval=TRUE}
```

```{r child = "01_cours_modlin.Rmd", eval=TRUE}
```


```{r child = "02_cours_modlin.Rmd", eval=TRUE}
```
```{r var_select, child = "02.1_cours_modlin.Rmd", eval=TRUE}
```

```{r child = "03_cours_modlin.Rmd", eval=TRUE}
```

```{r child = "04_cours_modlin.Rmd", eval=FALSE}
```

```{r child = "0Biblio  _cours_modlin.Rmd", eval=TRUE}
```

```{r, results="verbatim"}
sessionInfo()
```



